version: '3.8'

services:
  consul:
    image: consul
    container_name: consul
    ports:
      - "8500:8500" # Consul UI
      - "8600:8600" # DNS
    command: agent -server -ui -client='0.0.0.0'
    networks:
      - dream

  etcd:
    image: quay.io/coreos/etcd
    container_name: etcd
    init: true
    ports:
      - "2379:2379"
    volumes:
      - ../data/etcd/data:/etcd-data
    environment:
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://192.168.134.128:2379"
      ETCD_TTL: "10"
    networks:
      - dream


  nacos:
    image: nacos/nacos-server
    container_name: nacos
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ../data/nacos/logs:/home/nacos/logs        # 挂载日志目录
      - ../data/nacos/data:/home/nacos/data        # 挂载数据目录
    networks:
      - dream

networks:
  dream:
    driver: bridge